name: Lint

on:
    pull_request:

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
    
          - name: Set up Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '18'
              cache: 'yarn'
    
          # Install dependencies and run linter for the client
          - name: Install dependencies for client
            working-directory: ./client
            run: yarn install
          - name: Run linter for client
            working-directory: ./client
            run: yarn lint
    
          # Install dependencies and run linter for the server
          - name: Install dependencies for server
            working-directory: ./server
            run: yarn install
          - name: Run linter for server
            working-directory: ./server
            run: yarn lint
